# Basic
title: Harry Lee
subtitle: 「所有的記憶都是潮濕的」
welcome_message: 嗨，我是秋奇，歡迎來到我的個人網誌
description: 關注科技與人文
creator: <a href="http://qiuqi.li">@Harry Lee</a>

url: "http://qiuqi.li"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: 博客
    description: visit blog

# Navigation buttons in the front page.
nav:
    - {title: 关于, description: about me, url: 'http://qiuqi.li'}
    - {title: 订阅, description: follow me, url: 'http://qiuqi.li/feed.xml'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: qiuqi-li
    # duoshuo: 
    
# Social
social:
    weibo: letusq7
    github: HarryLee-BJ
    twitter: Qiuqi_Li
    gplus: 114002840711275844877
    mail: mail@qiuqi.li

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host

theme: jekyll-theme-tactile